#J2
set_property -dict {PACKAGE_PIN G27 IOSTANDARD LVCMOS18} [get_ports o_la01_p]
set_property -dict {PACKAGE_PIN F30 IOSTANDARD LVCMOS18} [get_ports i_la00_p]
set_property -dict {PACKAGE_PIN E27 IOSTANDARD LVCMOS18} [get_ports o_la06_p]
set_property -dict {PACKAGE_PIN G28 IOSTANDARD LVCMOS18} [get_ports o_la01_n]
set_property -dict {PACKAGE_PIN B30 IOSTANDARD LVCMOS18} [get_ports o_la03_p]
set_property -dict {PACKAGE_PIN D27 IOSTANDARD LVCMOS18} [get_ports o_la06_n]
set_property -dict {PACKAGE_PIN F29 IOSTANDARD LVCMOS18} [get_ports o_la05_p]
set_property -dict {PACKAGE_PIN J27 IOSTANDARD LVCMOS18} [get_ports i_la13_p]
set_property -dict {PACKAGE_PIN F28 IOSTANDARD LVCMOS18} [get_ports o_la09_n]
set_property -dict {PACKAGE_PIN F27 IOSTANDARD LVCMOS18} [get_ports o_la09_p]
set_property -dict {PACKAGE_PIN E29 IOSTANDARD LVCMOS18} [get_ports o_la05_n]
set_property -dict {PACKAGE_PIN L29 IOSTANDARD LVCMOS18} [get_ports o_la10_n]
set_property -dict {PACKAGE_PIN J28 IOSTANDARD LVCMOS18} [get_ports i_la13_n]
set_property -dict {PACKAGE_PIN L28 IOSTANDARD LVCMOS18} [get_ports o_la10_p]
set_property -dict {PACKAGE_PIN B27 IOSTANDARD LVCMOS18} [get_ports o_la14_p]
set_property -dict {PACKAGE_PIN AP22 IOSTANDARD LVCMOS18} [get_ports o_la17_p]
set_property -dict {PACKAGE_PIN AK24 IOSTANDARD LVCMOS18} [get_ports i_la33_n]
set_property -dict {PACKAGE_PIN AJ23 IOSTANDARD LVCMOS18} [get_ports o_la33_p]
set_property -dict {PACKAGE_PIN AM25 IOSTANDARD LVCMOS18} [get_ports o_la29_n]
set_property -dict {PACKAGE_PIN AL24 IOSTANDARD LVCMOS18} [get_ports o_la29_p]
set_property -dict {PACKAGE_PIN AN25 IOSTANDARD LVCMOS18} [get_ports i_la25_n]
set_property -dict {PACKAGE_PIN AN24 IOSTANDARD LVCMOS18} [get_ports o_la25_p]
set_property -dict {PACKAGE_PIN AV25 IOSTANDARD LVCMOS18} [get_ports o_la27_n]
set_property -dict {PACKAGE_PIN AU25 IOSTANDARD LVCMOS18} [get_ports o_la27_p]
set_property -dict {PACKAGE_PIN AR25 IOSTANDARD LVCMOS18} [get_ports o_la26_p]
set_property -dict {PACKAGE_PIN AT25 IOSTANDARD LVCMOS18} [get_ports i_la26_n]
set_property -dict {PACKAGE_PIN AP23 IOSTANDARD LVCMOS18} [get_ports o_la23_n]
set_property -dict {PACKAGE_PIN AN23 IOSTANDARD LVCMOS18} [get_ports o_la23_p]
set_property -dict {PACKAGE_PIN AR24 IOSTANDARD LVCMOS18} [get_ports o_la18_n]
set_property -dict {PACKAGE_PIN AP24 IOSTANDARD LVCMOS18} [get_ports o_la18_p]

#J3
set_property -dict {PACKAGE_PIN AL25 IOSTANDARD LVCMOS18} [get_ports i_la31_n]
set_property -dict {PACKAGE_PIN AK25 IOSTANDARD LVCMOS18} [get_ports o_la31_p]
set_property -dict {PACKAGE_PIN AK22 IOSTANDARD LVCMOS18} [get_ports o_la28_n]
set_property -dict {PACKAGE_PIN AJ22 IOSTANDARD LVCMOS18} [get_ports o_la28_p]
set_property -dict {PACKAGE_PIN AN26 IOSTANDARD LVCMOS18} [get_ports o_la24_n]
set_property -dict {PACKAGE_PIN AM26 IOSTANDARD LVCMOS18} [get_ports i_la24_p]
set_property -dict {PACKAGE_PIN AM23 IOSTANDARD LVCMOS18} [get_ports o_la21_n]
set_property -dict {PACKAGE_PIN AL23 IOSTANDARD LVCMOS18} [get_ports o_la21_p]
set_property -dict {PACKAGE_PIN AU22 IOSTANDARD LVCMOS18} [get_ports o_la22_n]
set_property -dict {PACKAGE_PIN AT22 IOSTANDARD LVCMOS18} [get_ports o_la22_p]
set_property -dict {PACKAGE_PIN AW24 IOSTANDARD LVCMOS18} [get_ports i_la19_n]
set_property -dict {PACKAGE_PIN AV24 IOSTANDARD LVCMOS18} [get_ports o_la19_p]
set_property -dict {PACKAGE_PIN AV23 IOSTANDARD LVCMOS18} [get_ports o_la20_n]
set_property -dict {PACKAGE_PIN AU23 IOSTANDARD LVCMOS18} [get_ports o_la20_p]
set_property -dict {PACKAGE_PIN A28 IOSTANDARD LVCMOS18} [get_ports o_la15_n]
set_property -dict {PACKAGE_PIN B28 IOSTANDARD LVCMOS18} [get_ports i_la15_p]
set_property -dict {PACKAGE_PIN E30 IOSTANDARD LVCMOS18} [get_ports o_la00_n]
set_property -dict {PACKAGE_PIN A29 IOSTANDARD LVCMOS18} [get_ports o_la02_p]
set_property -dict {PACKAGE_PIN A30 IOSTANDARD LVCMOS18} [get_ports o_la02_n]
set_property -dict {PACKAGE_PIN B31 IOSTANDARD LVCMOS18} [get_ports o_la03_n]
set_property -dict {PACKAGE_PIN B32 IOSTANDARD LVCMOS18} [get_ports i_la04_p]
set_property -dict {PACKAGE_PIN A32 IOSTANDARD LVCMOS18} [get_ports o_la04_n]
set_property -dict {PACKAGE_PIN D29 IOSTANDARD LVCMOS18} [get_ports o_la08_p]
set_property -dict {PACKAGE_PIN C29 IOSTANDARD LVCMOS18} [get_ports o_la08_n]
set_property -dict {PACKAGE_PIN C30 IOSTANDARD LVCMOS18} [get_ports o_la07_p]
set_property -dict {PACKAGE_PIN C31 IOSTANDARD LVCMOS18} [get_ports i_la07_n]
set_property -dict {PACKAGE_PIN K29 IOSTANDARD LVCMOS18} [get_ports o_la12_p]
set_property -dict {PACKAGE_PIN J29 IOSTANDARD LVCMOS18} [get_ports o_la12_n]
set_property -dict {PACKAGE_PIN L25 IOSTANDARD LVCMOS18} [get_ports o_la11_p]
set_property -dict {PACKAGE_PIN K25 IOSTANDARD LVCMOS18} [get_ports o_la11_n]
set_property -dict {PACKAGE_PIN K26 IOSTANDARD LVCMOS18} [get_ports i_la16_p]
set_property -dict {PACKAGE_PIN J26 IOSTANDARD LVCMOS18} [get_ports o_la16_n]

#J4
set_property -dict {PACKAGE_PIN H28 IOSTANDARD LVCMOS18} [get_ports i_clk0_m2c_p]
set_property -dict {PACKAGE_PIN H29 IOSTANDARD LVCMOS18} [get_ports o_clk0_m2c_n]
set_property -dict {PACKAGE_PIN AP26 IOSTANDARD LVCMOS18} [get_ports i_clk1_m2c_p]
set_property -dict {PACKAGE_PIN AR26 IOSTANDARD LVCMOS18} [get_ports o_clk1_m2c_n]

#J6
set_property -dict {PACKAGE_PIN N25 IOSTANDARD LVCMOS18} [get_ports o_sync_c2m_p]
set_property -dict {PACKAGE_PIN M25 IOSTANDARD LVCMOS18} [get_ports o_sync_c2m_n]
set_property -dict {PACKAGE_PIN R25 IOSTANDARD LVCMOS18} [get_ports o_sync_m2c_p]
set_property -dict {PACKAGE_PIN R26 IOSTANDARD LVCMOS18} [get_ports o_sync_m2c_n]
set_property -dict {PACKAGE_PIN AJ26 IOSTANDARD LVCMOS18} [get_ports o_la30_p]
set_property -dict {PACKAGE_PIN AK26 IOSTANDARD LVCMOS18} [get_ports o_la30_n]
set_property -dict {PACKAGE_PIN AH24 IOSTANDARD LVCMOS18} [get_ports i_la32_p]
set_property -dict {PACKAGE_PIN AJ24 IOSTANDARD LVCMOS18} [get_ports o_la32_n]
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS18} [get_ports o_la14_n]
set_property -dict {PACKAGE_PIN AR22 IOSTANDARD LVCMOS18} [get_ports i_la17_n]

#DACIO
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS18} [get_ports o_dacio00]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS18} [get_ports o_dacio01]
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS18} [get_ports o_dacio02]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS18} [get_ports o_dacio03]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVCMOS18} [get_ports o_dacio04]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS18} [get_ports i_dacio05]
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS18} [get_ports o_dacio06]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS18} [get_ports o_dacio07]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS18} [get_ports i_dacio08]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVCMOS18} [get_ports o_dacio09]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS18} [get_ports o_dacio10]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS18} [get_ports o_dacio11]
set_property -dict {PACKAGE_PIN E14 IOSTANDARD LVCMOS18} [get_ports i_dacio12]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS18} [get_ports o_dacio13]
set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS18} [get_ports o_dacio14]
set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVCMOS18} [get_ports o_dacio15]

#ADCIO
set_property -dict {PACKAGE_PIN AP10 IOSTANDARD LVCMOS18} [get_ports o_adcio00]
set_property -dict {PACKAGE_PIN AP11 IOSTANDARD LVCMOS18} [get_ports o_adcio01]
set_property -dict {PACKAGE_PIN AR11 IOSTANDARD LVCMOS18} [get_ports o_adcio02]
set_property -dict {PACKAGE_PIN AP12 IOSTANDARD LVCMOS18} [get_ports i_adcio03]
set_property -dict {PACKAGE_PIN AT10 IOSTANDARD LVCMOS18} [get_ports o_adcio04]
set_property -dict {PACKAGE_PIN AR10 IOSTANDARD LVCMOS18} [get_ports o_adcio05]
set_property -dict {PACKAGE_PIN AT12 IOSTANDARD LVCMOS18} [get_ports o_adcio06]
set_property -dict {PACKAGE_PIN AR12 IOSTANDARD LVCMOS18} [get_ports o_adcio07]
set_property -dict {PACKAGE_PIN AU11 IOSTANDARD LVCMOS18} [get_ports o_adcio08]
set_property -dict {PACKAGE_PIN AU12 IOSTANDARD LVCMOS18} [get_ports o_adcio09]
set_property -dict {PACKAGE_PIN AV10 IOSTANDARD LVCMOS18} [get_ports i_adcio10]
set_property -dict {PACKAGE_PIN AU10 IOSTANDARD LVCMOS18} [get_ports o_adcio11]
set_property -dict {PACKAGE_PIN AW9 IOSTANDARD LVCMOS18} [get_ports o_adcio12]
set_property -dict {PACKAGE_PIN AV9 IOSTANDARD LVCMOS18} [get_ports o_adcio13]
set_property -dict {PACKAGE_PIN AW11 IOSTANDARD LVCMOS18} [get_ports o_adcio14]
set_property -dict {PACKAGE_PIN AV11 IOSTANDARD LVCMOS18} [get_ports o_adcio15]

# PMOD
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS18} [get_ports o_pmod00]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS18} [get_ports o_pmod01]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS18} [get_ports o_pmod02]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS18} [get_ports o_pmod03]
set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVCMOS18} [get_ports o_pmod04]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS18} [get_ports o_pmod05]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS18} [get_ports o_pmod06]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS18} [get_ports i_pmod07]

set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS18} [get_ports i_pmod10]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS18} [get_ports o_pmod11]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS18} [get_ports o_pmod12]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS18} [get_ports o_pmod13]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS18} [get_ports o_pmod14]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS18} [get_ports o_pmod15]
set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVCMOS18} [get_ports o_pmod16]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS18} [get_ports o_pmod17]

# LED R
set_property -dict {PACKAGE_PIN AN14 IOSTANDARD LVCMOS12} [get_ports o_rled0]
set_property -dict {PACKAGE_PIN AP16 IOSTANDARD LVCMOS12} [get_ports o_rled1]
set_property -dict {PACKAGE_PIN AP14 IOSTANDARD LVCMOS12} [get_ports o_rled2]
set_property -dict {PACKAGE_PIN AU16 IOSTANDARD LVCMOS12} [get_ports o_rled3]
set_property -dict {PACKAGE_PIN AW12 IOSTANDARD LVCMOS12} [get_ports o_rled4]
set_property -dict {PACKAGE_PIN AY16 IOSTANDARD LVCMOS12} [get_ports o_rled5]
set_property -dict {PACKAGE_PIN BB12 IOSTANDARD LVCMOS12} [get_ports o_rled6]
set_property -dict {PACKAGE_PIN E25 IOSTANDARD LVCMOS12} [get_ports o_rled7]

# LED G
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS18} [get_ports o_gled0]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS18} [get_ports o_gled1]
set_property -dict {PACKAGE_PIN D12 IOSTANDARD LVCMOS18} [get_ports o_gled2]
set_property -dict {PACKAGE_PIN D13 IOSTANDARD LVCMOS18} [get_ports o_gled3]
set_property -dict {PACKAGE_PIN AW18 IOSTANDARD LVCMOS12} [get_ports o_gled4]
set_property -dict {PACKAGE_PIN AV18 IOSTANDARD LVCMOS12} [get_ports o_gled5]
set_property -dict {PACKAGE_PIN BA19 IOSTANDARD LVCMOS12} [get_ports o_gled6]
set_property -dict {PACKAGE_PIN AP21 IOSTANDARD LVCMOS12} [get_ports o_gled7]

# LED B
set_property -dict {PACKAGE_PIN B26 IOSTANDARD POD12_DCI} [get_ports o_bled0]
set_property -dict {PACKAGE_PIN E24 IOSTANDARD LVCMOS12} [get_ports o_bled1]
set_property -dict {PACKAGE_PIN G26 IOSTANDARD LVCMOS12} [get_ports o_bled2]
set_property -dict {PACKAGE_PIN J23 IOSTANDARD LVCMOS12} [get_ports o_bled3]
set_property -dict {PACKAGE_PIN L24 IOSTANDARD LVCMOS12} [get_ports o_bled4]
set_property -dict {PACKAGE_PIN P21 IOSTANDARD LVCMOS12} [get_ports o_bled5]
set_property -dict {PACKAGE_PIN AV21 IOSTANDARD LVCMOS12} [get_ports o_bled6]
set_property -dict {PACKAGE_PIN AR21 IOSTANDARD LVCMOS12} [get_ports o_bled7]

# button
set_property -dict {PACKAGE_PIN K12 IOSTANDARD LVCMOS18} [get_ports i_btn_w]
set_property -dict {PACKAGE_PIN K11 IOSTANDARD LVCMOS18} [get_ports i_btn_c]
#set_property -dict {PACKAGE_PIN J12 IOSTANDARD LVCMOS18} [get_ports i_btn_e]
#set_property CLOCK_BUFFER_TYPE NONE [get_ports i_btn_e]
#set_property CLOCK_BUFFER_TYPE NONE [get_ports i_btn_c]

create_clock -period 10.000 -waveform {0.000 5.000} [get_ports i_pl_clk_p]
set_property -dict {PACKAGE_PIN E10 IOSTANDARD LVDS_25} [get_ports i_pl_clk_p]

# fpga uart
set_property -dict {PACKAGE_PIN C10 IOSTANDARD LVCMOS18} [get_ports i_rx]
set_property -dict {PACKAGE_PIN B10 IOSTANDARD LVCMOS18} [get_ports o_tx]

#set_property PACKAGE_PIN D4 [get_ports i_dac1_clk_p]
#set_property PACKAGE_PIN D1 [get_ports i_sysref_n]
#set_property PACKAGE_PIN M5 [get_ports o_vout20_p]

#set_property -dict {PACKAGE_PIN E9 IOSTANDARD LVDS_25} [get_ports i_pl_clk_n]
#set_property -dict {PACKAGE_PIN E10 IOSTANDARD LVDS_25} [get_ports i_pl_clk_p]

#create_clock -add -name pl_clk -period 10.00 -waveform {0 5} [get_ports { i_pl_clk_p }];